export const AppRoute = {
    MAIN: '/nav/main',

    STOREINFOMATION: '/nav/store/information',
    OWNERACCOUNT: '/nav/store/owner/account',
    STORETYPE: '/nav/store/store/storeType',
    STORENOTICE: '/nav/store/store/storeNotice',
    STOREALERT: '/nav/store/store/storeAlert',
    STOREORIGINNOTICE: '/nav/store/store/storeOriginNotice',
    STORELOGO: '/nav/store/store/logo',
    STOREIMAGES: '/nav/store/store/images',
    STOREHOLIDAY: '/nav/store/store/holiday',
    STOREPICKUPZONE: '/nav/store/store/pickupzone',
    STOREPICKUPIMAGE: '/nav/store/store/pickupzone/image',
    STOREPICKUPZONEDETAIL: '/nav/store/store/pickupzone/detail',
    STOREORDERTIME: '/nav/store/store/ordertime',
    STOREOPERATIONTIME: '/nav/store/store/operationTime',
    MENU: '/nav/store/store/product',
    ACTIVATION: '/nav/store/activation',

    HOME: '/nav/home',

    NOTICE: '/nav/notice',
    COUPON: '/nav/coupon',
    COMMERCIAL: '/nav/commercial',
    STAMP: '/nav/stamp',
    ORDER: '/nav/order',
    CHAT: '/nav/order/chat',
    QUICKMANAGE: '/nav/quick/manage',
    QUICKINSERT: '/nav/quick/insert',
    ORDERLIST: '/nav/orderList',
    INVENTORY: '/nav/inventory',
    PRINTER: '/nav/printer',
    SETTINGS: '/nav/setting',
};
